<?php

namespace AppBundle\Repository;

/**
 * DonorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DonorsRepository extends \Doctrine\ORM\EntityRepository
{
}
