<?php

namespace AppBundle\Repository;

/**
 * HospitalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospitalsRepository extends \Doctrine\ORM\EntityRepository
{
	
	public function loadUserByAuthToken($token){
		$phno = base64_decode($token);
		
		$q = $this
		->createQueryBuilder('h')
		->where('h.phno = :phno')
		->setParameter('phno', $phno)
		->getQuery()
		;
	
		try {
			$hospital = $q->getSingleResult();
		} catch (\Exception $e) {
			throw new HttpException(Response::HTTP_INTERNAL_SERVER_ERROR, $e->getMessage());
		}
		return $hospital;
	}
}
