<?php

namespace AppBundle\Repository;

/**
 * HospitalsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HospitalsRepository extends \Doctrine\ORM\EntityRepository
{
}
