<?php

namespace AppBundle\Repository;

/**
 * LastDontationsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LastDonationsRepository extends \Doctrine\ORM\EntityRepository
{
}
