<?php

namespace AppBundle\Repository;

/**
 * RequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestsRepository extends \Doctrine\ORM\EntityRepository
{
}
