<?php

namespace AppBundle\Repository;

/**
 * RequestsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestsRepository extends \Doctrine\ORM\EntityRepository
{
	const STATUS_PENDING = 0;
	const STATUS_COMPLETE = 1;
}
